use dw_shop;
CREATE EXTERNAL TABLE IF NOT EXISTS DW_shop.DW_DETAIL_Shop_Products(
ProductId               bigint,
ProductName             string,
ProductCode             string,
CategoryId              int,
CategoryName            string,
TypeId                  int,
TypeName                string,
BrandId                 int,
BrandName               string,
BrandSpell              string,
SupplierId              int,
UserId                  int,
UserName                string,
SupplierName            string,
RegionId                int,
RegionName              string,
RegionCityId            int,
RegionCity              string,
RegionProvinceId        int,
RegionProvince          string,
DepotId                int,
Longitude              double,
Latitude               double,
shortdescription        string, 
unit                    string, 
description             string, 
meta_title              string, 
meta_description        string, 
meta_keywords           string,
salestatus              int,    
addeddate               timestamp, 
visticounts             int,  
salecounts              int,   
stock                   int,   
displaysequence         int,   
lineid                  int,   
marketprice             decimal(15,4),
lowestsaleprice         decimal(15,4),
penetrationstatus       int,   
maincategorypath        string,
extendcategorypath      string,
hassku                  boolean,
points                  double,
imageurl                string,
thumbnailurl1           string,
thumbnailurl2           string,
thumbnailurl3           string,
thumbnailurl4           string,
thumbnailurl5           string,
thumbnailurl6           string,
thumbnailurl7           string,
thumbnailurl8           string,
maxquantity             int ,  
minquantity             int ,  
tags                    string,
seourl                  string,
seoimagealt             string,
seoimagetitle           string,
salestype               int   ,
restrictioncount        int   ,
deliverytip             string,
remark                  string,
producttype             int   ,
salestatussub           int   ,
barcode                 string,
updateddate             timestamp
)ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LOCATION '/opt/data/hive/dw_shop/DW_DETAIL_Shop_Products';

INSERT  OVERWRITE TABLE DW_DETAIL_Shop_Products
SELECT
 t1.ProductId,
 t1.ProductName,
 t1.ProductCode,
 t1.CategoryId,
 t2.Name,
 t1.TypeId,
 t3.TypeName,
 t1.BrandId,
 t4.BrandName,
 t4.BrandSpell,
 t1.SupplierId,
 t5.UserId,
 t5.UserName,
 t5.Name,
 t1.RegionId,
 t6.RegionName,
 t6.RegionCityId  ,  
 t6.RegionCity ,     
 t6.RegionProvinceId,
 t6.RegionProvince,
 t6.DepotId ,  
 t6.Longitude ,  
 t6.Latitude ,  
 t1.shortdescription,
 t1.unit      ,      
 t1.description  ,   
 t1.meta_title     , 
 t1.meta_description,
 t1.meta_keywords   ,
 t1.salestatus    ,  
 t1.addeddate     ,  
 t1.visticounts   ,  
 t1.salecounts    ,  
 t1.stock         ,  
 t1.displaysequence ,
 t1.lineid        ,  
 t1.marketprice    , 
 t1.lowestsaleprice ,
 t1.penetrationstatus,
 t1.maincategorypath,
 t1.extendcategorypath,
 t1.hassku   ,       
 t1.points  ,        
 t1.imageurl    ,    
 t1.thumbnailurl1,
 t1.thumbnailurl2,  
 t1.thumbnailurl3,  
 t1.thumbnailurl4,  
 t1.thumbnailurl5,  
 t1.thumbnailurl6,  
 t1.thumbnailurl7,  
 t1.thumbnailurl8,  
 t1.maxquantity ,    
 t1.minquantity ,    
 t1.tags   ,         
 t1.seourl ,         
 t1.seoimagealt ,    
 t1.seoimagetitle ,  
 t1.salestype   ,    
 t1.restrictioncount,
 t1.deliverytip   ,  
 t1.remark   ,       
 t1.producttype ,    
 t1.salestatussub ,  
 t1.barcode   ,      
 t1.updateddate 
From ods_shop.ODS_Shop_Products t1 
LEFT JOIN ods_shop.ODS_Shop_Categories t2  on  t1.CategoryId = t2.CategoryId
LEFT JOIN ods_shop.ODS_Shop_ProductTypes t3  on t1.TypeId = t3.TypeId
LEFT JOIN ods_shop.ODS_Shop_Brands t4 on t1.BrandId = t4.BrandId
LEFT JOIN ods_shop.ODS_Shop_Suppliers t5 on t1.SupplierId = t5.SupplierId
LEFT JOIN dw_shop.dw_wide_shop_regiondepot t6 on t1.RegionId = t6.RegionID; 