INSERT INTO TABLE dw_shop.DW_Shop_Items
partition(dt="${hivevar:dtime}")
SELECT
  t1.`orderid` ,
  t1.`ordercode`,
  t1.`parentorderid`  ,
  t1.`createddate` , 
  to_date(`createddate`),
  t1.`updateddate` , 
  t1.`buyerid`  ,
  t1.`buyername`,
  t1.`buyeremail`  ,
  t1.`buyercellphone` ,
  t1.`regionid` ,
  t3.`regionname`,
  t3.`regionCityId`,
  t3.`regionCity`,
  t3.`regionProvinceId`,
  t3.`regionProvince`,
  t3.`longitude`,
  t3.`latitude`,
  t1.`shipregion`  ,
  t1.`shipaddress` ,
  t1.`shipzipcode` ,
  t1.`shipname` ,
  t1.`shiptelphone`,
  t1.`shipcellphone`  ,
  t1.`shipemail`,
  t1.`shippingmodeid` ,
  t1.`shippingmodename`  , 
  t1.`realshippingmodeid`,
  t1.`realshippingmodename` , 
  t1.`shipperid`,
  t1.`shippername`,
  t1.`shipperaddress`,
  t1.`shippercellphone` ,
  t1.`shippingstatus`,
  t1.`shipordernumber`  ,
  t1.`expresscompanyname`  ,
  t1.`expresscompanyabb`,
  t1.`paymenttypeid` ,
  t1.`paymenttypename`  ,
  t1.`paymentgateway`,
  t1.`paymentstatus` ,
  t1.`refundstatus`  ,
  t1.`amount`  , 
  t1.`ordertype`  ,
  t1.`orderstatus`,
  t1.`sellerid`  ,
  t1.`sellername`,
  t1.`selleremail`  ,
  t1.`sellercellphone` ,
  t1.`supplierid`,
  t1.`suppliername` ,
  t1.`orderip`,
  t1.`remark` ,
  t1.`producttotal` ,
  t1.`haschildren`  ,
  t1.`isreviews` ,
  t1.`refertype` ,
  t1.`createuserid` ,
  t1.`originalid`,
  t1.`ordertypesub` ,
  t1.`refername` ,
  t1.`ordermode` ,
  t1.`lineid` ,
  t1.`linename`  ,
  t1.`depotid`,
  t1.`depotname` ,
  t2.itemid,
  t2.productid ,
  t2.productcode  ,
  t2.sku ,
  t2.name,
  t2.quantity  ,
  t2.shipmentquantity,
  t2.costprice ,
  t2.sellprice ,
  t2.adjustedprice,
  t2.attribute ,
  t2.weight ,
  t2.deduct ,
  t2.points ,
  t2.productlineid,
  t2.brandid,
  t2.brandname ,
  t2.producttype  ,
  t2.discountprice,
  t2.buysku
FROM dw_shop.DW_Wide_Shop_RegionDepot t3 
RIGHT JOIN (select * from ods_shop.ods_shop_orders where to_date(`createddate`)=date_sub(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),1)) t1
ON (t1.regionid = t3.regionid)
RIGHT JOIN ods_shop.ODS_Shop_OrderItems t2 
ON (t1.orderid = t2.orderid );