CREATE EXTERNAL TABLE IF NOT EXISTS dw_shop.DW_SaleOrderBillDetail(
  `id` bigint, 
  `batchmoney` double,
  `batchnum` string, 
  `batchprice` double, 
  `billcode` string, 
  `blgift` boolean, 
  `blproxy` boolean, 
  `costmoney` double, 
  `costoperateway` string, 
  `costprice` double, 
  `expirydate` string, 
  `jwh` string, 
  `money` double, 
  `oldbillcode` string, 
  `oldbillordinal` int, 
  `ordinal` int, 
  `piececostprice` double, 
  `pieceprice` double, 
  `pieceqty` int, 
  `price` double, 
  `profit` double, 
  `qty` double, 
  `qtyofpackage` int, 
  `rates` double, 
  `retailmoney` double, 
  `retailprice` double, 
  `returncause` string, 
  `scatteredqty` int, 
  `specification` string, 
  `tradeprice` double, 
  `unit` string, 
  `bill_id` bigint, 
  `saletype` int, 
  `blsolutiongroupfirst` boolean, 
  `promotionalsolution` string, 
  `solutiongroupid` string, 
  `solutionqty` double, 
  `solutionmultiple` int, 
  `solutionpieceqty` int, 
  `solutionscatteredqty` int, 
  `promotional_solution_id` bigint, 
  `deftotalpieceqty` int, 
  `solutiontype` string, 
  `orderitemordinal` int, 
  `deliverfee` double, 
  `piecedeliverfee` double, 
  `blborrow` boolean, 
  `remailqty` int, 
  `realprice` double, 
  `realmoney` double, 
  `allowancemoney` double,
  `deliver ` string,
  `driver ` string,
  `exhibitDate` date,
  `makeDate ` date,
  `operator` string,
  `salesman` string,
  `vehCode` string,
  `ent_id ` bigint,
  `kokura_id ` bigint,
  `kokura_name ` bigint,
  `goods_id` bigint,
  `goods_name` string,
  `store_id ` bigint,
  `store_name` string
  )
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LOCATION '/opt/data/hive/dw_shop/DW_SaleOrderBillDetail';  

INSERT OVERWRITE table dw_shop.DW_SaleOrderBillDetail
SELECT  
  t1.`id` , 
  t1.`batchmoney` , 
  t1.`batchnum` , 
  t1.`batchprice` , 
  t1.`billcode` , 
  t1.`blgift` , 
  t1.`blproxy` , 
  t1.`costmoney` , 
  t1.`costoperateway` , 
  t1.`costprice` , 
  t1.`expirydate` , 
  t1.`jwh` , 
  t1.`money` , 
  t1.`oldbillcode` , 
  t1.`oldbillordinal` , 
  t1.`ordinal` , 
  t1.`piececostprice` , 
  t1.`pieceprice` , 
  t1.`pieceqty` , 
  t1.`price` , 
  t1.`profit` , 
  t1.`qty` , 
  t1.`qtyofpackage` , 
  t1.`rates` , 
  t1.`retailmoney` , 
  t1.`retailprice` , 
  t1.`returncause` , 
  t1.`scatteredqty` , 
  t1.`specification` , 
  t1.`tradeprice` , 
  t1.`unit` , 
  t1.`bill_id` , 
  t1.`saletype` , 
  t1.`blsolutiongroupfirst` , 
  t1.`promotionalsolution` , 
  t1.`solutiongroupid` , 
  t1.`solutionqty` , 
  t1.`solutionmultiple` , 
  t1.`solutionpieceqty` , 
  t1.`solutionscatteredqty` , 
  t1.`promotional_solution_id` , 
  t1.`deftotalpieceqty` , 
  t1.`solutiontype` , 
  t1.`orderitemordinal` , 
  t1.`deliverfee` , 
  t1.`piecedeliverfee` , 
  t1.`blborrow` , 
  t1.`remailqty` , 
  t1.`realprice` , 
  t1.`realmoney` , 
  t1.`allowancemoney` ,
  t2.`deliver` ,
  t2.`driver` ,
  t2.`exhibitDate` ,
  t2.`makeDate` ,
  t2.`operator` ,
  t2.`salesman` ,
  t2.`vehCode` ,
  t2.`ent_id` ,
  t2.`kokura_id`,
  t3.`name`,
  t1.`goods_id`,
  t4.`productName`,
  t1.`store_id`,
  t5.`name`
FROM  ods_shop.ODS_SaleOrderBillDetail t1 LEFT JOIN ods_shop.ODS_SaleOrderBill t2
on t1.bill_id = t2.id
LEFT JOIN ods_shop.ODS_Erp_Depot t3 on t2.kokura_id = t3.depotid
LEFT JOIN ods_shop.ODS_Shop_Products t4 on t1.goods_id = t4.productid
LEFT JOIN ods_shop.ODS_Store t5 on t5.id = t1.store_id;