CREATE EXTERNAL TABLE IF NOT EXISTS dw_shop.DW_Shop_Items(
`orderid` int, 
`ordercode`       string, 
`parentorderid`   int, 
`createddate`     timestamp,
`orderdate`       date ,
`updateddate`     timestamp, 
`buyerid`         int, 
`buyername`       string, 
`buyeremail`      string, 
`buyercellphone`  string, 
`regionid`        int, 
`regionname`      string,
`regionCityId`    int,
`regionCity`      string,
`regionProvinceId` int,
`regionProvince`   string,
`longitude`      double,
`latitude`       double,
`shipregion`      string, 
`shipaddress`     string, 
`shipzipcode`     string, 
`shipname`        string, 
`shiptelphone`    string, 
`shipcellphone`   string, 
`shipemail`       string, 
`shippingmodeid`     int, 
`shippingmodename`   string, 
`realshippingmodeid` int, 
`realshippingmodename` string, 
`shipperid`            int, 
`shippername`         string, 
`shipperaddress`      string, 
`shippercellphone`    string, 
`shippingstatus`      smallint, 
`shipordernumber`     string, 
`expresscompanyname`  string, 
`expresscompanyabb`   string, 
`paymenttypeid`       int, 
`paymenttypename`     string, 
`paymentgateway`      string, 
`paymentstatus`       smallint, 
`refundstatus`        smallint, 
`amount`              decimal(15,4), 
`ordertype`           smallint, 
`orderstatus`         smallint, 
`sellerid`            int, 
`sellername`      string, 
`selleremail`     string, 
`sellercellphone` string, 
`supplierid`      int, 
`suppliername`    string, 
`orderip`         string, 
`remark`          string, 
`producttotal`    decimal(15,4), 
`haschildren`     boolean, 
`isreviews`       boolean, 
`refertype`       int, 
`createuserid`    int, 
`originalid`      bigint, 
`ordertypesub`    smallint, 
`refername`       string, 
`ordermode`       int, 
`lineid`          int, 
`linename`        string, 
`depotid`         int, 
`depotname`       string,
itemid              bigint,
productid               bigint,
productcode             string,
sku                     string,
name                    string,
quantity                int   ,
shipmentquantity        int   ,
costprice               decimal(15,4),
sellprice               decimal(15,4),
adjustedprice           decimal(15,4),
attribute               string,
weight                  int   ,
deduct                  double,
points                  int   ,
productlineid           int   ,
brandid                 int   ,
brandname               string,
producttype             int   ,
discountprice           decimal(15,4),
buysku                  string
)PARTITIONED BY(DT string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LOCATION '/opt/data/hive/dw_shop/DW_Shop_Items';

set hive.exec.dynamic.partition=true;
set hive.exec.dynamic.partition.mode=nostrick;
set hive.exec.max.dynamic.partitions.pernode=1000;

INSERT OVERWRITE TABLE dw_shop.DW_Shop_Items
partition(dt)
SELECT
  t1.`orderid` ,
  t1.`ordercode`,
  t1.`parentorderid`  ,
  t1.`createddate` ,
  to_date(`createddate`),
  t1.`updateddate` , 
  t1.`buyerid`  ,
  t1.`buyername`,
  t1.`buyeremail`  ,
  t1.`buyercellphone` ,
  t1.`regionid` ,
  t3.`regionname`,
  t3.`regionCityId`,
  t3.`regionCity`,
  t3.`regionProvinceId`,
  t3.`regionProvince`,
  t3.`longitude`,
  t3.`latitude`,
  t1.`shipregion`  ,
  t1.`shipaddress` ,
  t1.`shipzipcode` ,
  t1.`shipname` ,
  t1.`shiptelphone`,
  t1.`shipcellphone`  ,
  t1.`shipemail`,
  t1.`shippingmodeid` ,
  t1.`shippingmodename`  , 
  t1.`realshippingmodeid`,
  t1.`realshippingmodename` , 
  t1.`shipperid`,
  t1.`shippername`,
  t1.`shipperaddress`,
  t1.`shippercellphone` ,
  t1.`shippingstatus`,
  t1.`shipordernumber`  ,
  t1.`expresscompanyname`  ,
  t1.`expresscompanyabb`,
  t1.`paymenttypeid` ,
  t1.`paymenttypename`  ,
  t1.`paymentgateway`,
  t1.`paymentstatus` ,
  t1.`refundstatus`  ,
  t1.`amount`  , 
  t1.`ordertype`  ,
  t1.`orderstatus`,
  t1.`sellerid`  ,
  t1.`sellername`,
  t1.`selleremail`  ,
  t1.`sellercellphone` ,
  t1.`supplierid`,
  t1.`suppliername` ,
  t1.`orderip`,
  t1.`remark` ,
  t1.`producttotal` ,
  t1.`haschildren`  ,
  t1.`isreviews` ,
  t1.`refertype` ,
  t1.`createuserid` ,
  t1.`originalid`,
  t1.`ordertypesub` ,
  t1.`refername` ,
  t1.`ordermode` ,
  t1.`lineid` ,
  t1.`linename`  ,
  t1.`depotid`,
  t1.`depotname` ,
  t2.itemid,
  t2.productid ,
  t2.productcode  ,
  t2.sku ,
  t2.name,
  t2.quantity  ,
  t2.shipmentquantity,
  t2.costprice ,
  t2.sellprice ,
  t2.adjustedprice,
  t2.attribute ,
  t2.weight ,
  t2.deduct ,
  t2.points ,
  t2.productlineid,
  t2.brandid,
  t2.brandname ,
  t2.producttype  ,
  t2.discountprice,
  t2.buysku,
  to_date(t1.`createddate`)dt
FROM dw_shop.DW_Wide_Shop_RegionDepot t3 
RIGHT JOIN (select * from ods_shop.ods_shop_orders where to_date(`createddate`)>'2016-06-01') t1
ON (t1.regionid = t3.regionid)
RIGHT JOIN ods_shop.ODS_Shop_OrderItems t2 
ON (t1.orderid = t2.orderid );
