CREATE EXTERNAL TABLE IF NOT EXISTS ods_shop.`ODS_StockStoreBill` (
  `id` bigint ,
  `billCode` string,
  `billMoney` double,
  `billType` string,
  `blProxy` int,
  `chequeNum` string,
  `contractNum` string,
  `deliver` string,
  `driver` string,
  `flowFlag` int,
  `invoiceNum` string,
  `killMoney` double ,
  `lockName` string,
  `oldBillCode` string,
  `operator` string,
  `outInMoney` double,
  `payMoney` double,
  `remainMoney` double,
  `remarks` string,
  `salesman` string,
  `storeDate` TIMESTAMP,
  `trafficNum` string,
  `vehCode` string,
  `ent_id` bigint,
  `stockOrderBill_id` bigint,
  `sys_dep_id` bigint,
  `kokura_id` bigint,
  `storeTime` timestamp ,
  `stockMoney` double,
  `deliveryBillCode` string,
  `operator_id` bigint,
  `salesman_id` bigint,
  `discountMoney` double,
  `discountFeeRate` double 
) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LOCATION '/opt/data/hive/ods_shop/ODS_stockstorebill';
