CREATE EXTERNAL TABLE IF NOT EXISTS ods_shop.ODS_Shop_Products
(
categoryid              int,   
typeid                  int,    
productid               bigint, 
brandid                 int,    
productname             string, 
productcode             string, 
supplierid              int,    
regionid                int,    
shortdescription        string, 
unit                    string, 
description             string, 
meta_title              string, 
meta_description        string, 
meta_keywords           string,
salestatus              int,    
addeddate               string, 
visticounts             int,  
salecounts              int,   
stock                   int,   
displaysequence         int,   
lineid                  int,   
marketprice             decimal(15,4),
lowestsaleprice         decimal(15,4),
penetrationstatus       int,   
maincategorypath        string,
extendcategorypath      string,
hassku                  boolean,
points                  double,
imageurl                string,
thumbnailurl1           string,
thumbnailurl2           string,
thumbnailurl3           string,
thumbnailurl4           string,
thumbnailurl5           string,
thumbnailurl6           string,
thumbnailurl7           string,
thumbnailurl8           string,
maxquantity             int ,  
minquantity             int ,  
tags                    string,
seourl                  string,
seoimagealt             string,
seoimagetitle           string,
salestype               int   ,
restrictioncount        int   ,
deliverytip             string,
remark                  string,
producttype             int   ,
salestatussub           int   ,
barcode                 string,
updateddate             string
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LOCATION '/opt/data/hive/ods_shop/ODS_Shop_Products';